import type { DurationType, PreferenceType } from '../../config/product';

export type { DurationType, PreferenceType };

/**
 * A geographic cluster or walkable neighborhood in Daejeon.
 */
export interface Zone {
  id: string;
  name: string;
  description?: string;
  active: boolean;
}

/**
 * A single stop within a recommended travel route.
 */
export interface RouteStop {
  order: number;
  placeId: string;
  name: string;
  category: string;
  durationMin: number;
  travelMin?: number;
}

/**
 * Complete recommended itinerary generated by the Controlled Random Travel engine.
 * Variable stop count supported across different templates and durations.
 */
export interface RouteResult {
  id: string;
  zoneId: string;
  durationType: DurationType;
  preference: PreferenceType;
  stops: RouteStop[];
  mission?: string;
  createdAt: string;
}

/**
 * Candidate place definition for the recommendation pool.
 */
export interface PlaceCandidate {
  id: string;
  name: string;
  category: string;
  zoneId: string;
  durationMin: number;
  tags: string[];
  roles?: CandidateRole[];
  address?: string;
  mapUrl?: string;
  image?: string;
  description?: string;
  active: boolean;
}

/**
 * Conceptual role assigned to a slot in a route template.
 */
export type CandidateRole = 'anchor' | 'meal' | 'discovery' | 'stay-extender';

/**
 * Definition of a structured route template composed of ordered role slots.
 */
export interface RouteTemplate {
  id: string;
  duration: DurationType;
  targetPreference?: PreferenceType;
  slots: CandidateRole[];
}

/**
 * Input options for generating a controlled random route.
 */
export interface GenerateRouteOptions {
  durationType: DurationType;
  preference: PreferenceType;
  zones: Zone[];
  candidates: PlaceCandidate[];
  random?: () => number;
}
