import type { DurationType, PreferenceType } from '../../config/product';

export type { DurationType, PreferenceType };

/**
 * A geographic cluster or walkable neighborhood in Daejeon.
 */
export interface Zone {
  id: string;                    // Zone identifier (e.g., "daeheung-station")
  name: string;                  // Display name (e.g., "대전역·은행·대흥")
  description?: string;
  centerCoords?: { lat: number; lng: number };
  active: boolean;
}

/**
 * Provider-neutral external map links.
 */
export interface PlaceMapLinks {
  naver?: string;
  kakao?: string;
}

/**
 * A single stop within a recommended travel route.
 * Conforms to docs/DATA_MODEL.md section 2.3.
 */
export interface RouteStop {
  order: number;                 // 1-based stop sequence (1, 2, 3, 4)
  placeId: string;               // Reference to PlaceCandidate
  name: string;                  // Place name
  category: string;              // Category tag
  stayDurationMin: number;       // Estimated stay time at place (minutes)
  travelToNextMin?: number;      // Estimated transit time to next stop (minutes)
  transitMode?: 'walk' | 'transit' | 'taxi'; // Recommended transit mode
  address?: string;
  mapLinks?: PlaceMapLinks;      // External map links (provider-neutral)
  tips?: string;                 // Playful tip or caution (operational text -- Route Guide only, never Result)
  hook?: string;                 // Resolved short attraction copy for Result StopCard (candidate.hook, falling back to a genre tag) -- never operational text
}

/**
 * Complete recommended itinerary generated by the Controlled Random Travel engine.
 * Variable stop count supported across different templates and durations.
 * Conforms to docs/DATA_MODEL.md section 2.3.
 */
export interface RouteResult {
  id: string;                    // Ephemeral client route ID
  zoneId: string;                // Recommended zone
  zoneName: string;              // Display zone name
  durationType: DurationType;
  preference: PreferenceType;
  title: string;                 // Curated headline (e.g., "오늘은 대흥동 먹방 코스!")
  stops: RouteStop[];            // Variable sequence of 1–4 stops
  mission?: string;              // Optional playful travel mission
  estimatedTotalMinutes: number; // Sum of place stay durations + inter-stop travel times
  createdAt: string;             // ISO-8601 timestamp
}

/**
 * Conceptual role assigned to a place candidate in the recommendation pool.
 */
export type CandidateRole = 'anchor' | 'meal' | 'discovery' | 'stay-extender';

/**
 * Ordered route slot type within an itinerary template.
 * Distinct from candidate-level conceptual roles.
 */
export type RouteSlot = 'meal' | 'cafe' | 'discovery' | 'preference';

/**
 * Candidate place definition for the recommendation pool.
 */
export interface PlaceCandidate {
  id: string;                    // Unique place identifier (e.g., "sungsimdang-main")
  name: string;                  // Display name (e.g., "성심당 본점")
  category: string;              // Primary category (e.g., "베이커리", "카페", "명소")
  zoneId: string;                // Zone association (e.g., "eunhaeng-daeheung")
  durationMin: number;           // Typical stay duration in minutes (e.g., 45)
  tags: string[];                // Search and preference filter tags
  roles?: CandidateRole[];       // Engine role classification
  address?: string;              // Physical road address in Daejeon
  mapLinks?: PlaceMapLinks;      // Outbound external map links (provider-neutral)
  mapUrl?: string;               // Optional legacy/generic map URL fallback
  image?: string;                // Optional image asset path
  description?: string;          // Curated one-line description (operational: hours/break/last order/parking/waiting -- Route Guide only, never Result)
  hook?: string;                 // Optional short attraction "hook" copy for Result StopCard; falls back to a genre tag when absent
  active: boolean;               // Availability flag
}

/**
 * Definition of a structured route template composed of ordered slots.
 * Conforms to docs/DATA_MODEL.md section 2.2.
 */
export interface RouteTemplate {
  id: string;                    // Template ID (e.g., "half_ordered_3", "full_ordered_4")
  zoneId?: string;               // Optional zone association (if zone-specific)
  durationType: DurationType;   // 'half' | 'full'
  preference?: PreferenceType;   // Target preference filter ('anything' | 'food' | 'walk' | 'photo')
  targetDurationMin?: { min: number; max: number }; // Configurable duration budget range (TBD)
  slots: RouteSlot[];            // Ordered route slot sequence (e.g., ['meal', 'cafe', 'preference'])
}

/**
 * Immutable snapshot of an itinerary stop for referral sharing.
 */
export interface SharedRouteStopSnapshot {
  order: number;
  placeId: string;
  name: string;
  category: string;
  stayDurationMin: number;
  travelToNextMin?: number;
  transitMode?: string;
  address?: string;
  mapLinks?: PlaceMapLinks;
  tips?: string;
}

/**
 * Immutable snapshot of a generated route saved for referral sharing (/r/[shareCode]).
 */
export interface RouteSnapshot {
  sourceRouteId: string;        // Ephemeral route ID at time of generation
  zoneId: string;               // Recommended zone
  durationType: DurationType;
  preferenceType: PreferenceType;
  title: string;                // Route title snapshot
  stops: SharedRouteStopSnapshot[]; // Immutable stop sequence snapshot
  mission?: string;             // Travel mission snapshot
  estimatedTotalMinutes: number;// Total estimated travel time
  schemaVersion: number;        // Data contract schema version (default 1)
}

/**
 * 7-Day Today's Pick item definition.
 */
export interface TodaysPickItem {
  id: string;                    // Pick identifier (e.g., "pick-01-soje")
  slug: string;                  // URL slug for /pick/[slug] (e.g., "soje-dong-cafe")
  campaignDate: string;          // Target active date in YYYY-MM-DD (Asia/Seoul)
  title: string;                 // Headline (e.g., "소제동 철도관사촌 골목 산책")
  subtitle: string;              // Short description / vibe hook
  pixelAsset: string;            // Pixel artwork path for Landing frame
  characterId: string;           // Kkumssi family character ID / asset key (e.g., "kkumdori")
  characterAsset?: string;       // Direct character artwork path (if mapped)
  photos: string[];              // Real photography asset paths for Detail page
  tags: string[];                // Tag list (e.g., ["#철도관사", "#카페거리", "#포토존"])
  recommendedPreference: PreferenceType; // Pre-seeding target for Q2
  recommendationReason: string;  // Curated one-line recommendation reason
  stayDuration: string;          // Display stay time (e.g., "약 1시간 30분")
  recommendedTime: string;       // Recommended visiting time (e.g., "오후 2시 ~ 5시")
  access: string;                // Transit guide (e.g., "대전역 동광장 도보 5분")
  caution: string;               // Practical visitor tip/caution
  mapLinks?: PlaceMapLinks;      // Outbound external map links (provider-neutral)
}

/**
 * Reroll reward state.
 */
export type RerollRewardState = 'locked' | 'available' | 'consumed';

/**
 * Client session state for the 1-time reroll reward lifecycle.
 */
export interface RerollSessionState {
  routeSessionId: string;        // Ephemeral identifier for the active travel session
  rerollReward: RerollRewardState; // Initial: 'locked'
  unlockedAt?: string;           // ISO timestamp of successful guestbook submission
  consumedAt?: string;           // ISO timestamp of second spin execution
  awardedRouteId?: string;       // Route ID for which the reroll was unlocked
}

/**
 * Input options for generating a controlled random route.
 */
export interface GenerateRouteOptions {
  durationType: DurationType;
  preference: PreferenceType;
  zones: Zone[];
  candidates: PlaceCandidate[];
  random?: () => number;
}
